name: Update data

on:
  schedule:
    - cron: "10 15 * * *"
  workflow_dispatch:


jobs:
  update:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install dependencies
        run: |
         install.packages(c("shiny","ggplot2","xlsx","readxl","dplyr","shinyWidgets","shinythemes","ggpubr","see","DT","stringr","tidyr","labelled","ggrepel","lubridate","data.table"))          
        shell: Rscript {0}
      - name: Make data
        run: |
                    source("make_data.R")
        shell: Rscript {0}
      - name: Mining intervention
        run: |
                    source("mining_intervention.R")
        shell: Rscript {0}
      - name: Data update
        run: |
                    source("data_update.R")
        shell: Rscript {0}
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -m "add data"
          git push  
          
          
