name: Update data

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  obs:
  update:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install dependencies
        run: |
         install.packages(c("shiny","ggplot2","xlsx","readxl","tidyverse","dplyr","shinyWidgets",
         "shinythemes","ggpubr","see","kableExtra","DT","shinysky","labelled","ggrepel","shinymanager","lubridate"))          
        shell: Rscript {0}
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -m "add data"
          git push  
          
          
